#--------Data--------
DATA_PATH : 'data/Hamlyn/rectified01/image01_50' #whatever dataset
DATA_TYPE : 'folder' #folder, video
#--------GT----------
GT_PATH : 'data/Hamlyn/rectified01/depth01' #whatever dataset
#--------Scheme------
SELECT_SCHEME: 
- 'rchannel' #rchannel, feature, quality

DEPTH_SCHEME: 'endo-depth' #depth-anything|endo-depth
#--------Color-------
RC_THRESHOLD: 127
#--------Quality-----
Q_METHOD: 'hyperIQA'
#--------Hyper-IQA---
IQA_THRESHOLD: 40
#--------Depth Anything---
DA_ENCODER: vitl
PRED_ONLY: True
GRAY_SCALE: True
#--------Endo Depth---
ED_MODEL: 'epoch8'
#--------Reconstruction---
RECON_METHOD: 'ICP'
DEPTH_FOLDER: 'temp' #default to be using temp
USE_GPU: True
fx: 383.1901395
fy: 
cx:
cy:
SMALL_POINT_THRESHOLD: 0.01
ICP_MAX_ITERATION: 200



#--------Visual------
IF_MUTE: False
