#--------Data--------
DATA_PATH : 'data/Hamlyn/rectified01/image01_50' #whatever dataset
DATA_TYPE : 'folder' #folder, video
#--------Scheme------
SELECT_SCHEME: 
- 'quality' #color-r, feature, quality

DEPTH_SCHEME: 'depth-anything' #should only be one value and here it is 
#--------Color-------
R_THRESHOLD: 127
#--------Quality-----
Q_METHOD: 'hyperIQA'
#--------Hyper-IQA---
IQA_THRESHOLD: 40
#--------Depth Anything---
DA_ENCODER: vitl
PRED_ONLY: True
GRAY_SCALE: True
#--------Reconstruction---
RECON_METHOD: 'ICP'
DEPTH_FOLDER: 'temp' #default to be using temp
USE_GPU: True
fx: 383.1901395
fy: 
cx:
cy:
SMALL_POINT_THRESHOLD: 0.01
ICP_MAX_ITERATION: 200



#--------Visual------
IF_MUTE: False
