#--------Data--------
DATA_PATH : 'data/Hamlyn/rectified17/image01_last45' #whatever dataset
DATA_TYPE : 'folder' #folder, video
#--------GT----------
GT_PATH : 'data/Hamlyn/rectified17/depth01' #whatever dataset
#--------Scheme------
SELECT_SCHEME: 
#rchannel, feature, quality

DEPTH_SCHEME: 'depth-anything:v2' #endo-dac|depth-anything|endo-depth|depth-anything:v2
#--------Color-------
RC_THRESHOLD: 127
#--------Quality-----
Q_METHOD: 'hyperIQA'
#--------Hyper-IQA---
IQA_THRESHOLD: 40
#--------Depth Anything---
DA_ENCODER: vitl
PRED_ONLY: True
GRAY_SCALE: True
#--------Endo Depth---
ED_MODEL: 'epoch8'
#--------Endo-DAC---
EDAC_GPU: True
EDAC_MODEL: './EndoDAC_fullmodel'
#--------Reconstruction---
SKIP_RECON: False
RECON_METHOD: 'ICP'
DEPTH_FOLDER: 'temp' #default to be using temp
USE_GPU: True
NEED_REVERSE: True
fx: 383.1901395
fy: 
cx: 0.51
cy:
SMALL_POINT_THRESHOLD: 0.01
ICP_MAX_ITERATION: 200



#--------Visual------
IF_MUTE: False
