#--------Data--------
DATA_PATH : 'data/Hamlyn/rectified01/image01_50' #whatever dataset
DATA_TYPE : 'folder' #folder, video
#--------Scheme------
SELECT_SCHEME: 
- 'quality' #color-r, feature, quality

DEPTH_SCHEME: 'depth-anything' #should only be one value and here it is 
#--------Color-------
R_THRESHOLD: 127
#--------Quality-----
Q_METHOD: 'hyperIQA'
#--------Hyper-IQA---
IQA_THRESHOLD: 40
#--------Depth Anything---
DA_ENCODER: vitl
PRED_ONLY: True
GRAY_SCALE: True

#--------Visual------
IF_MUTE: True
